### ISSUE TITLE
ActivityAlarmSchedulerBinding unsolved reference

### ISSUE THREAD

**Issue by nicolaslohan** [salvatop/simple-alarm#2]
Importation of "app.salvatop.simplealarm.databinding.ActivityAlarmSchedulerBinding" show problem with the 'databinding' directory that doesn't exists, if it's even a directory. How do I solve this?

**Comment by lke1221** [comment]
Same problem here

**Comment by Scythal** [comment]
Yes, there are many problems with this "example".

For the databinding, the resource must be a layout. I don't know why the author chose databinding here, since a simple viewbinding would have done perfectly.

So change the following file:

src/main/res/layout/activity_alarm_scheduler.xml

so that the top looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools">
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".AlarmScheduler">
```

and of course, insert a ```</layout>``` at the end.

Anyway, there are many other issues, the best you can do is disregard this application and find a better example.

**Comment by salvatop** [comment]
I'm sorry for the issue you have going through, this is never meant to be an example to follow, it was more an experiment to understand how the databinding was working applied on a small project that i had. 

I never had the time to fix this so I will delete the repo, and Like Scythal suggested it would be better find other example for databinding.
